# To use:
#
#   $ micromamba env create -f environment.yml  # `conda` works too for this command
#   $ micromamba activate eonpydev
#
name: eonpydev
channels:
  - conda-forge
dependencies:
  - compilers
  - meson
  - cmake
  - ninja
  - gfortran
  - pkg-config
  - openblas
  # Pinned
  - eigen==3.4.0
  # AMS
  - boost-cpp
  - fmt<10.0.0
  - spdlog
  - abseil-cpp
  # Testing
  - pytest
  - pytest-datadir
  # Extras
  - numpy
  - ase
  - PyYAML
  - pytest
  - pytest-datadir
  - sh
  - sphinx
  - towncrier
  # Lint
  - cppcheck
  - cpplint
  # eonPy
  - pybind11
